[package]
name = "palettebot"
version = "0.1.0"
authors = ["Andra Antariksa <andra.antariksa@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
imageproc = "0.18.0"
rand = "0.6.5"
pexels = "0.1.2"
reqwest = "0.9.16"